### ISSUE TITLE
Checksum invalid or type unrecognised on habitat genpayload wizzard

### ISSUE THREAD

**Issue by zanco** [df8oe/STM32_RTTY#7]
Hi, for the last 6 months or so I get this error when I try to create a payload doc with this RS41HUP version.

> Checksum invalid or type unrecognised. Tried xor crc16-ccitt fletcher-16 fletcher-16-256

I have no clue why this happens. Any help please ?

Thanks,
Ben

**Comment by df8oe** [comment]
I have no idea, too. Checksum is calculated using CRC-16 and OVER ALL FILEDS (included RTTY comment - maybe that's the problem??). I have just tested - checksum is generated properly.

Best regards
Andreas

**Comment by ED6E0F17** [comment]
The checksum was broken by the commit: https://github.com/df8oe/RS41HUP/commit/1ca9174a91a3e0393b438552db53bc1db5cf2263

which removed a single "$" from the start of RTTY string without changing the offset in :
 https://github.com/df8oe/RS41HUP/blob/master/main.c#L234

**Comment by df8oe** [comment]
Many thanks. This was never intended - it was a typo.

Fixed now.
